### ISSUE TITLE
Can we get the paper here in advance?

### ISSUE THREAD

**Issue by saladcat** [mengliu1998/DeeperGNN#1]
Thanks for sharing your awesome work, but I can't find the paper here.
would you like to release pdf version of the paper? or you can share it with me. My email is djytyang@Gmail.com.

Thanks anyway

**Comment by mengliu1998** [comment]
Thank you for your interest.

Our camera-ready paper has been submitted to ACM and it will be available soon.

**Comment by saladcat** [comment]
Thanks anyway😁

**Comment by mengliu1998** [comment]
Our paper is now available on [arXiv](https://arxiv.org/abs/2007.09296).

Thank you.

**Comment by saladcat** [comment]
Got it.
Thank you
