### ISSUE TITLE
PyG version

### ISSUE THREAD

**Issue by drzhang3** [mengliu1998/DeeperGNN#2]
HI, could you please provide the version of PyG?   I met an error "`AttributeError: type object 'GCNConv' has no attribute 'norm'`" when I ran the code.

**Comment by mengliu1998** [comment]
Sure.

I used torch_geometric 1.3.1. 

However, 'GCNConv.norm' has been removed in the latest version. (1) You can downgrade torch_geometric to the old version, or, (2) you can add the 'norm' in 1.3.1 as a function in the current dagnn.py.

```Python
from torch_scatter import scatter_add
from torch_geometric.utils import add_remaining_self_loops

def sym_norm(edge_index, num_nodes, edge_weight=None, improved=False, dtype=None):
    if edge_weight is None:
        edge_weight = torch.ones((edge_index.size(1), ), dtype=dtype, device=edge_index.device)

    fill_value = 1 if not improved else 2
    edge_index, edge_weight = add_remaining_self_loops(edge_index, edge_weight, fill_value, num_nodes)

    row, col = edge_index
    deg = scatter_add(edge_weight, row, dim=0, dim_size=num_nodes)
    deg_inv_sqrt = deg.pow(-0.5)
    deg_inv_sqrt[deg_inv_sqrt == float('inf')] = 0

    return edge_index, deg_inv_sqrt[row] * edge_weight * deg_inv_sqrt[col]
```  

Then, change the line 34 in dagnn.py from
```Python
edge_index, norm = GCNConv.norm(edge_index, x.size(0), edge_weight, dtype=x.dtype)
```
to
```Python
edge_index, norm = sym_norm(edge_index, x.size(0), edge_weight, dtype=x.dtype)
```

**Comment by drzhang3** [comment]
Thanks for your reply.

**Comment by EtoDemerzel0427** [comment]
why not simply use the `gcn_norm` in [torch_geometric/nn/conv/gcn_conv.py](https://github.com/rusty1s/pytorch_geometric/blob/ec70a3f14fef9cdbf7284c6d2010db6999d26572/torch_geometric/nn/conv/gcn_conv.py#L30)?

**Comment by mengliu1998** [comment]
@EtoDemerzel0427 

In earlier PyG versions (such as 1.3.1), there is no independent gcn_norm function in torch_geometric/nn/conv/gcn_conv.py, and the "norm" is implemented as a method in GCN class. We incorporate this function explicitly in our code so that this code can work smoothly in different PyG environment (>= 1.3.1).
